name: minecap
main: minecraft.Minecap
version: 1.0
author: land00000
commands:
    $:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.trade
       permission-message: You don't have <permission>
    buy:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.buy
       permission-message: You don't have <permission>
    sell:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.sell
       permission-message: You don't have <permission>
    claim:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.claim
       permission-message: You don't have <permission>
