name: minecap
main: minecraft.Minecap
version: 1.0
author: land00000
commands:
    $:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.trade
       permission-message: You don't have <permission>
    browse:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.browse
       permission-message: You don't have <permission>
    escrow:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.escrow
       permission-message: You don't have <permission>
