name: minecap
main: minecraft.Minecap
version: 1.0
author: land00000
commands:
    $:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.trade
       permission-message: You don't have <permission>
    buyers:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.buyers
       permission-message: You don't have <permission>
    sellers:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.sellers
       permission-message: You don't have <permission>
    claim:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.claim
       permission-message: You don't have <permission>
    trade:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.trade
       permission-message: You don't have <permission>
    lookup:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.lookup
       permission-message: You don't have <permission>
    myorders:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.myorders
       permission-message: You don't have <permission>
    cancel:
       description: This is a demo command.
       usage: /<command>
       permission: minecap.cancel
       permission-message: You don't have <permission>
